### ISSUE TITLE
[Feature Request] Bulk downloading

### ISSUE THREAD

**Issue by ImNoahDev** [yogeshwaran01/lyricy#8]
Feature Request:
Add the ability to mass download LRC files for many songs in multiple directories. This will allow you to run it for your whole plex library to download lyrics for every song in every album directory

**Comment by yogeshwaran01** [comment]
It may add wrong lyrics to the track. You use this as [Python package](https://github.com/yogeshwaran01/lyricy#python-package)

Try this script

```python
import os
from lyricy import Lyricy

l = Lyricy()

directory = './path/to/directory'  # Replace with the directory path you want to search

# Get all files in the directory
files = []
for root, _, filenames in os.walk(directory):
    for filename in filenames:
        files.append(filename)

for file in files:
    results = l.search(file.split('.')[0])
    selected_lyrics = results[0]
    selected_lyrics.fetch()
    selected_lyrics.add_to_track(file)
    print('done')

```
